//TODOD NOTES
export const ADD_NOTES = 'ADD_NOTES';
export const CURRENT_NOTE = 'CURRENT_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const ACHIVED_NOTE = 'ACHIVED_NOTE';
 


//TODO ERRORS
export const NOTE_VALIDATE ='NOTE_VALIDATE';